// Bundles the browser libraries into public/vendor so the site needs no build
// step and loads nothing from third-party CDNs (except Plaid Link, which must
// come from Plaid). Run after upgrading preact, htm or firebase:
//
//   npm run vendor

import { build } from 'esbuild';
import { mkdirSync, writeFileSync } from 'node:fs';

mkdirSync('public/vendor', { recursive: true });

const entries = {
  'preact.js': `
    export * from 'preact';
    export * from 'preact/hooks';
    import htm from 'htm';
    import { h } from 'preact';
    export const html = htm.bind(h);
  `,
  'firebase-auth.js': `
    export { initializeApp } from 'firebase/app';
    export {
      getAuth, GoogleAuthProvider, signInWithPopup, signInWithRedirect, getRedirectResult,
      onAuthStateChanged, signOut, connectAuthEmulator, browserLocalPersistence, setPersistence, signInWithCredential,
    } from 'firebase/auth';
  `,
};

for (const [file, contents] of Object.entries(entries)) {
  await build({
    stdin: { contents, resolveDir: process.cwd(), loader: 'js' },
    bundle: true,
    format: 'esm',
    minify: true,
    target: ['es2022'],
    legalComments: 'none',
    outfile: `public/vendor/${file}`,
    logLevel: 'warning',
  });
  console.log(`built public/vendor/${file}`);
}
writeFileSync('public/vendor/README.md', 'Generated by `npm run vendor` (scripts/build-vendor.js). Do not edit.\n');
